## this is a sample docker compose configuration
---
version: '3'

services:
  postgres:
    image: dldldldl/zombodb:latest
    build:
      context: .
      dockerfile: Dockerfile
      ## PG_VER is optional, default value: 13
      # args:
      #   PG_VER: '12'
    environment:
      POSTGRES_PASSWORD: 'postgresql'
    ports:
      - 5432:5432

  elasticsearch:
    image: elasticsearch:7.17.18
    ports:
      - 9200:9200
      ## 9300 port is for multi-node communication
      # - 9300:9300
    environment:
      - discovery.type=single-node
